export const years = [1999, 2002, 2006, 2010, 2014, 2019, 2024]
export const attributes = ['family', 'lrgen', 'lrecon', 'spendvtax', 'redistribution', 'deregulation', 'eu_position', 'eu_intmark',
  'eu_foreign', 'immigrate_policy', 'multiculturalism', 'ethnic_minorities', 'nationalism', 'civlib_laworder', 'sociallifestyle',
  'religious_principles', 'environment', 'urban_rural', 'regions'] // Reordered so that similar topics are close
export const factions = {
  1: 'Radical Right',
  2: 'Conservatives',
  3: 'Liberal',
  4: 'Christian-Democratic',
  5: 'Socialist',
  6: 'Radical Left',
  7: 'Green',
  8: 'Regionalist',
  9: 'No faction',
  10: 'Confessional',
  11: 'Agrarian/Center'
}
export const countries = {
  1: 'Belgium',
  2: 'Denmark',
  3: 'Germany',
  4: 'Greece',
  5: 'Spain',
  6: 'France',
  7: 'Ireland',
  8: 'Italy',
  10: 'Netherlands',
  11: 'UK',
  12: 'Portgual',
  13: 'Austria',
  14: 'Finland',
  16: 'Sweden',
  20: 'Bulgaria',
  21: 'Czechia',
  22: 'Estonia',
  23: 'Hungary',
  24: 'Latvia',
  25: 'Lithuania',
  26: 'Poland',
  27: 'Romania',
  28: 'Slovenia',
  29: 'Slovakia',
  31: 'Croatia',
  34: 'Türkiye',
  35: 'Norway',
  36: 'Switzerland',
  37: 'Malta',
  38: 'Luxembourg',
  40: 'Cyprus',
  45: 'Iceland'
}
