export const years = [1999, 2002, 2006, 2010, 2014, 2019, 2024]

export const attributes = {
  family: 'Political faction', // Reordered so that similar topics are close
  lrgen: 'Left/right',
  lrecon: 'Economic left/right',
  spendvtax: 'Spending vs. reducing taxes',
  redistribution: 'Wealth redistribution',
  deregulation: 'Market deregulation',
  eu_position: 'European Union',
  eu_intmark: 'EU internal market',
  eu_foreign: 'EU foreign policy',
  immigrate_policy: 'Immigration policies',
  multiculturalism: 'Multiculturalism',
  ethnic_minorities: 'Ethnic minorities',
  nationalism: 'Nationalism',
  civlib_laworder: 'Civil liberties vs. law & order',
  sociallifestyle: 'Social lifestyle',
  religious_principles: 'Religious principles',
  environment: 'Environment',
  urban_rural: 'Urban vs. rural',
  regions: 'Regionalism'
}
export const dropDownAttributes = {
  vote: 'Votes in the latest national election (%)',
  seat: 'Parliament seats in the latest national election (%)',
  epvote: 'Votes in the latest European election (%)',
  lrgen: 'Left/right',
  lrecon: 'Economic left/right',
  spendvtax: 'Spending vs. reducing taxes',
  redistribution: 'Wealth redistribution',
  deregulation: 'Market deregulation',
  eu_position: 'European Union',
  eu_intmark: 'EU internal market',
  eu_foreign: 'EU foreign policy',
  immigrate_policy: 'Immigration policies',
  multiculturalism: 'Multiculturalism',
  ethnic_minorities: 'Ethnic minorities',
  nationalism: 'Nationalism',
  civlib_laworder: 'Civil liberties vs. law & order',
  sociallifestyle: 'Social lifestyle',
  religious_principles: 'Religious principles',
  environment: 'Environment',
  urban_rural: 'Urban vs. rural',
  regions: 'Regionalism'
}

export const factions = {
  1: 'Radical Right',
  2: 'Conservatives',
  3: 'Liberal',
  4: 'Christian-Democratic',
  5: 'Socialist',
  6: 'Radical Left',
  7: 'Green',
  8: 'Regionalist',
  9: 'No faction',
  10: 'Confessional',
  11: 'Agrarian/Center'
}

export const countries = {
  1: 'Belgium',
  2: 'Denmark',
  3: 'Germany',
  4: 'Greece',
  5: 'Spain',
  6: 'France',
  7: 'Ireland',
  8: 'Italy',
  10: 'Netherlands',
  11: 'UK',
  12: 'Portgual',
  13: 'Austria',
  14: 'Finland',
  16: 'Sweden',
  20: 'Bulgaria',
  21: 'Czechia',
  22: 'Estonia',
  23: 'Hungary',
  24: 'Latvia',
  25: 'Lithuania',
  26: 'Poland',
  27: 'Romania',
  28: 'Slovakia',
  29: 'Slovenia',
  31: 'Croatia',
  34: 'Türkiye',
  35: 'Norway',
  36: 'Switzerland',
  37: 'Malta',
  38: 'Luxembourg',
  40: 'Cyprus',
  45: 'Iceland'
}
